INSERT INTO SYS_CODE (SYS_GROUP, SYS_NAME, SYS_VALUE, MEMO, CREATE_ID, CREATE_DATE, UPDATE_ID, UPDATE_DATE)
VALUES ('SYS', 'GIT_TOKEN', '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', '2024/8/29 expire', 'SYS', NOW(), null, null);

INSERT INTO BATCH_JOB_FLOW_CONTROL (JOB_NAME, STEP_NAME, STEP_ORDER, IS_EXECUTABLE)
VALUES ('ExampleJob', 'example1-step', 1, 'Y');
INSERT INTO BATCH_JOB_FLOW_CONTROL (JOB_NAME, STEP_NAME, STEP_ORDER, IS_EXECUTABLE)
VALUES ('ExampleJob', 'example2-step', 2, 'Y');

INSERT INTO BATCH_JOB_TRIGGER_CONFIG(JOB_NAME, JOB_DESC, BEAN_NAME, TRIGGER_NAME, CRON_TRIGGER, ENABLE, CREATE_ID, CREATE_DATE, UPDATE_ID, UPDATE_DATE)
VALUES ('ExampleJob', '範例作業', 'example-job', 'example-job-trigger', '0 * * * * ?', 'Y', 'SYS', NOW(), null, null);