DROP TABLE IF EXISTS SYS_CODE;
DROP TABLE IF EXISTS BATCH_JOB_FLOW_CONTROL;

CREATE TABLE SYS_CODE (
  SYS_GROUP VARCHAR(10) ,
  SYS_NAME VARCHAR(20) ,
  SYS_VALUE VARCHAR(250) ,
  MEMO VARCHAR(250) ,
  CREATE_ID VARCHAR(10) ,
  CREATE_DATE DATE ,
  UPDATE_ID VARCHAR(10) ,
  UPDATE_DATE DATE,
  PRIMARY KEY(SYS_GROUP,SYS_NAME)
);

CREATE TABLE BATCH_JOB_FLOW_CONTROL (
    JOB_NAME VARCHAR(50),
    STEP_NAME VARCHAR(50),
    STEP_ORDER INTEGER,
    IS_EXECUTABLE CHAR(1),
    PRIMARY KEY(JOB_NAME,STEP_NAME)
)